language: ruby
rvm:
  - 1.9.2
 env:
  - DB=sqlite
before_install: 
  - gem install debugger-linecache -v '1.1.1'
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace   
script: bundle exec rake 